### ISSUE TITLE
Error using IE11: SCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by scosmaa** [Kelin2025/vue-responsive-components#2]
When I use the component as a directive I get the error using IE11
I'm using Vue CLI 3

That is the code giving error running npm run serve:

/***/ "./node_modules/vue-responsive-components/index.js":
/*!*********************************************************!*\
  !*** ./node_modules/vue-responsive-components/index.js ***!
  \*********************************************************/
/*! exports provided: ResponsiveMixin, Responsive, ResponsiveDirective, VueResponsiveComponents */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* WEBPACK VAR INJECTION */(function(process) {/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"ResponsiveMixin\", function() { return ResponsiveMixin; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"Responsive\", function() { return Responsive; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"ResponsiveDirective\", function() { return ResponsiveDirective; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"VueResponsiveComponents\", function() { return VueResponsiveComponents; });\n/* harmony import */ var lodash_throttle__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! lodash.throttle */ \"./node_modules/lodash.throttle/index.js\");\n/* harmony import */ var lodash_throttle__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(lodash_throttle__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var resize_observer_polyfill__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! resize-observer-polyfill */ \"./node_modules/resize-observer-polyfill/dist/ResizeObserver.es.js\");\n\n\n\nconst ResponsiveMixin = {\n  data() {\n    return {\n      el: {\n        width: 0,\n        height: 0,\n        is: {}\n      }\n    }\n  },\n  mounted() {\n    if (\n      typeof process === \"undefined\" ||\n      (!process.server && (this.breakpoints || this.$options.breakpoints))\n    ) {\n      this.$nextTick(() => {\n        const handleResize = lodash_throttle__WEBPACK_IMPORTED_MODULE_0___default()(entries => {\n          const cr = entries[0].contentRect\n          ;(this.el.width = cr.width), (this.el.height = cr.height)\n          const conds = Object.assign(\n            {},\n            this.breakpoints || {},\n            this.$options.breakpoints || {}\n          )\n          for (const breakpoint in conds) {\n            this.$set(this.el.is, breakpoint, conds[breakpoint](this.el))\n          }\n        }, 200)\n\n        const observer = new resize_observer_polyfill__WEBPACK_IMPORTED_MODULE_1__[\"default\"](handleResize)\n        if (this.$el instanceof Element) {\n          observer.observe(this.$el)\n        }\n      })\n    }\n  }\n}\n\nconst Responsive = {\n  data() {\n    return { init: false }\n  },\n  props: {\n    noHide: { type: Boolean, default: false },\n    breakpoints: { type: Object, default: undefined }\n  },\n  mixins: [ResponsiveMixin],\n  render(h) {\n    const slot =\n      (this.$scopedSlots.default && this.$scopedSlots.default(this.el)) ||\n      this.$slots.default\n\n    return !this.noHide && !this.init\n      ? h(\n          \"div\",\n          {\n            style: { visibility: \"hidden\" }\n          },\n          [slot]\n        )\n      : slot\n  },\n  mounted() {\n    this.init = true\n  }\n}\n\nconst ResponsiveDirective = {\n  inserted(el, conds) {\n    if (typeof process === \"undefined\" || !process.server) {\n      const handleResize = lodash_throttle__WEBPACK_IMPORTED_MODULE_0___default()(entries => {\n        const cr = entries[0].contentRect\n        for (const breakpoint in conds.value) {\n          if (conds.value[breakpoint](cr)) {\n            el.classList.add(breakpoint)\n          } else {\n            el.classList.remove(breakpoint)\n          }\n        }\n      }, 200)\n\n      const observer = new resize_observer_polyfill__WEBPACK_IMPORTED_MODULE_1__[\"default\"](handleResize)\n      observer.observe(el)\n    }\n  }\n}\n\nconst VueResponsiveComponents = Vue => {\n  Vue.component(\"Responsive\", Responsive)\n  Vue.directive(\"responsive\", ResponsiveDirective)\n}\n\n/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../node-libs-browser/mock/process.js */ \"./node_modules/node-libs-browser/mock/process.js\")))//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9ub2RlX21vZHVsZXMvdnVlLXJlc3BvbnNpdmUtY29tcG9uZW50cy9pbmRleC5qcy5qcyIsInNvdXJjZXMiOlsid2VicGFjazovLy8uL25vZGVfbW9kdWxlcy92dWUtcmVzcG9uc2l2ZS1jb21wb25lbnRzL2luZGV4LmpzP2JlMjYiXSwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHRocm90dGxlIGZyb20gXCJsb2Rhc2gudGhyb3R0bGVcIlxuaW1wb3J0IFJlc2l6ZU9ic2VydmVyIGZyb20gXCJyZXNpemUtb2JzZXJ2ZXItcG9seWZpbGxcIlxuXG5leHBvcnQgY29uc3QgUmVzcG9uc2l2ZU1peGluID0ge1xuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICBlbDoge1xuICAgICAgICB3aWR0aDogMCxcbiAgICAgICAgaGVpZ2h0OiAwLFxuICAgICAgICBpczoge31cbiAgICAgIH1cbiAgICB9XG4gIH0sXG4gIG1vdW50ZWQoKSB7XG4gICAgaWYgKFxuICAgICAgdHlwZW9mIHByb2Nlc3MgPT09IFwidW5kZWZpbmVkXCIgfHxcbiAgICAgICghcHJvY2Vzcy5zZXJ2ZXIgJiYgKHRoaXMuYnJlYWtwb2ludHMgfHwgdGhpcy4kb3B0aW9ucy5icmVha3BvaW50cykpXG4gICAgKSB7XG4gICAgICB0aGlzLiRuZXh0VGljaygoKSA9PiB7XG4gICAgICAgIGNvbnN0IGhhbmRsZVJlc2l6ZSA9IHRocm90dGxlKGVudHJpZXMgPT4ge1xuICAgICAgICAgIGNvbnN0IGNyID0gZW50cmllc1swXS5jb250ZW50UmVjdFxuICAgICAgICAgIDsodGhpcy5lbC53aWR0aCA9IGNyLndpZHRoKSwgKHRoaXMuZWwuaGVpZ2h0ID0gY3IuaGVpZ2h0KVxuICAgICAgICAgIGNvbnN0IGNvbmRzID0gT2JqZWN0LmFzc2lnbihcbiAgICAgICAgICAgIHt9LFxuICAgICAgICAgICAgdGhpcy5icmVha3BvaW50cyB8fCB7fSxcbiAgICAgICAgICAgIHRoaXMuJG9wdGlvbnMuYnJlYWtwb2ludHMgfHwge31cbiAgICAgICAgICApXG4gICAgICAgICAgZm9yIChjb25zdCBicmVha3BvaW50IGluIGNvbmRzKSB7XG4gICAgICAgICAgICB0aGlzLiRzZXQodGhpcy5lbC5pcywgYnJlYWtwb2ludCwgY29uZHNbYnJlYWtwb2ludF0odGhpcy5lbCkpXG4gICAgICAgICAgfVxuICAgICAgICB9LCAyMDApXG5cbiAgICAgICAgY29uc3Qgb2JzZXJ2ZXIgPSBuZXcgUmVzaXplT2JzZXJ2ZXIoaGFuZGxlUmVzaXplKVxuICAgICAgICBpZiAodGhpcy4kZWwgaW5zdGFuY2VvZiBFbGVtZW50KSB7XG4gICAgICAgICAgb2JzZXJ2ZXIub2JzZXJ2ZSh0aGlzLiRlbClcbiAgICAgICAgfVxuICAgICAgfSlcbiAgICB9XG4gIH1cbn1cblxuZXhwb3J0IGNvbnN0IFJlc3BvbnNpdmUgPSB7XG4gIGRhdGEoKSB7XG4gICAgcmV0dXJuIHsgaW5pdDogZmFsc2UgfVxuICB9LFxuICBwcm9wczoge1xuICAgIG5vSGlkZTogeyB0eXBlOiBCb29sZWFuLCBkZWZhdWx0OiBmYWxzZSB9LFxuICAgIGJyZWFrcG9pbnRzOiB7IHR5cGU6IE9iamVjdCwgZGVmYXVsdDogdW5kZWZpbmVkIH1cbiAgfSxcbiAgbWl4aW5zOiBbUmVzcG9uc2l2ZU1peGluXSxcbiAgcmVuZGVyKGgpIHtcbiAgICBjb25zdCBzbG90ID1cbiAgICAgICh0aGlzLiRzY29wZWRTbG90cy5kZWZhdWx0ICYmIHRoaXMuJHNjb3BlZFNsb3RzLmRlZmF1bHQodGhpcy5lbCkpIHx8XG4gICAgICB0aGlzLiRzbG90cy5kZWZhdWx0XG5cbiAgICByZXR1cm4gIXRoaXMubm9IaWRlICYmICF0aGlzLmluaXRcbiAgICAgID8gaChcbiAgICAgICAgICBcImRpdlwiLFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHN0eWxlOiB7IHZpc2liaWxpdHk6IFwiaGlkZGVuXCIgfVxuICAgICAgICAgIH0sXG4gICAgICAgICAgW3Nsb3RdXG4gICAgICAgIClcbiAgICAgIDogc2xvdFxuICB9LFxuICBtb3VudGVkKCkge1xuICAgIHRoaXMuaW5pdCA9IHRydWVcbiAgfVxufVxuXG5leHBvcnQgY29uc3QgUmVzcG9uc2l2ZURpcmVjdGl2ZSA9IHtcbiAgaW5zZXJ0ZWQoZWwsIGNvbmRzKSB7XG4gICAgaWYgKHR5cGVvZiBwcm9jZXNzID09PSBcInVuZGVmaW5lZFwiIHx8ICFwcm9jZXNzLnNlcnZlcikge1xuICAgICAgY29uc3QgaGFuZGxlUmVzaXplID0gdGhyb3R0bGUoZW50cmllcyA9PiB7XG4gICAgICAgIGNvbnN0IGNyID0gZW50cmllc1swXS5jb250ZW50UmVjdFxuICAgICAgICBmb3IgKGNvbnN0IGJyZWFrcG9pbnQgaW4gY29uZHMudmFsdWUpIHtcbiAgICAgICAgICBpZiAoY29uZHMudmFsdWVbYnJlYWtwb2ludF0oY3IpKSB7XG4gICAgICAgICAgICBlbC5jbGFzc0xpc3QuYWRkKGJyZWFrcG9pbnQpXG4gICAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIGVsLmNsYXNzTGlzdC5yZW1vdmUoYnJlYWtwb2ludClcbiAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICAgIH0sIDIwMClcblxuICAgICAgY29uc3Qgb2JzZXJ2ZXIgPSBuZXcgUmVzaXplT2JzZXJ2ZXIoaGFuZGxlUmVzaXplKVxuICAgICAgb2JzZXJ2ZXIub2JzZXJ2ZShlbClcbiAgICB9XG4gIH1cbn1cblxuZXhwb3J0IGNvbnN0IFZ1ZVJlc3BvbnNpdmVDb21wb25lbnRzID0gVnVlID0+IHtcbiAgVnVlLmNvbXBvbmVudChcIlJlc3BvbnNpdmVcIiwgUmVzcG9uc2l2ZSlcbiAgVnVlLmRpcmVjdGl2ZShcInJlc3BvbnNpdmVcIiwgUmVzcG9uc2l2ZURpcmVjdGl2ZSlcbn1cbiJdLCJtYXBwaW5ncyI6IkFBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBIiwic291cmNlUm9vdCI6IiJ9\n//# sourceURL=webpack-internal:///./node_modules/vue-responsive-components/index.js\n");

/***/ }),

**Comment by Kelin2025** [comment]
Is that the whole error? I think something is missed

**Comment by scosmaa** [comment]
No, it isn't. It is a piece of my app.js. The error is the following. Do you need the app.js?
![image](https://user-images.githubusercontent.com/5979664/44729564-67297800-aadf-11e8-9bf3-1d588860f8ba.png)

**Comment by Kelin2025** [comment]
`vue-responsive-components` is not transpiled and published "as is"  
Maybe that is the problem, have you tried [**this solution**](https://github.com/Justineo/vue-awesome/issues/7#issuecomment-322034039)?  
I tried to install it to the fresh Nuxt project and it works fine

```js
      if (isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [
              /\.(?!(?:js|json)$).{1,5}$/i,
              /^vue-responsive-components/
            ]
          })
        ]
      }
```

**Comment by scosmaa** [comment]
Thank you, I'll try

**Comment by Kelin2025** [comment]
Any news here? I'll close it if problem is solved
